### ISSUE TITLE
swc archive has problems with python-swiftclient 3.0.0

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#21]
I only tested python3.5 and python-swiftclient 3.0.0

root@lxdtest1:~# swc archive /usr/bin /test13/archive
**\* uploading /usr/bin ***
**\* to AUTH_Swift__ADM_SciComp:/test13/archive ***
executing:swbundler.py -l "/usr/bin" -c test13 -p "archive" -t "/tmp/root.hQjuL" -P 2 
**\* please wait... ***
importing os.walk instead of scandir.walk
Traceback (most recent call last):
  File "/usr/local/bin/swbundler.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/swift_commander/swbundler.py", line 423, in main
    sub_tree,meta)
  File "/usr/local/lib/python3.5/dist-packages/swift_commander/swbundler.py", line 189, in archive_to_swift
    sw_post(container)
  File "/usr/local/lib/python3.5/dist-packages/swift_commander/swbundler.py", line 96, in sw_post
    sw_shell(shell.st_post,*args)
  File "/usr/local/lib/python3.5/dist-packages/swift_commander/swbundler.py", line 85, in sw_shell
    sw_fun(parser, list(args), output)
  File "/usr/local/lib/python3.5/dist-packages/swiftclient/shell.py", line 683, in st_post
    (options, args) = parse_args(parser, args)
  File "/usr/local/lib/python3.5/dist-packages/swiftclient/shell.py", line 1106, in parse_args
    if enforce_requires and (options.debug or options.info):
AttributeError: 'Values' object has no attribute 'debug'
error 1 uploading /usr/bin to /test13/archive

**Comment by dirkpetersen** [comment]
python3.5 is not the issue, it works with python-swiftclient 2.7

**Comment by dirkpetersen** [comment]
fixed
